-- ============================================================
-- Crédito para Startups — Seed
-- Execute APÓS o schema.sql no SQL Editor do Supabase
-- ============================================================

insert into public.categories (slug, name, description, position) values
  ('creditos', 'Créditos', 'Créditos de cloud, IA e ferramentas de desenvolvimento.', 1),
  ('programas', 'Programas', 'Programas oficiais para startups com créditos e suporte.', 2),
  ('editais', 'Editais', 'Editais e fomento público no Brasil.', 3),
  ('aceleradoras', 'Aceleradoras', 'Aceleradoras e hubs de inovação.', 4),
  ('perks', 'Perks & Benefícios', 'Descontos e planos gratuitos em ferramentas.', 5),
  ('inteligencia-artificial', 'Inteligência Artificial', 'Créditos e programas focados em IA.', 6),
  ('cloud', 'Cloud', 'Créditos de infraestrutura em nuvem.', 7),
  ('brasil', 'Brasil', 'Exclusivo para startups brasileiras.', 8)
on conflict (slug) do nothing;

insert into public.opportunities
  (slug, title, company, company_domain, category, tags, value_label, value_brl, short_description, description, eligibility, application_process, difficulty, external_url, featured, sponsored, published) values
  ('anthropic-claude-para-startups', 'Anthropic Claude para Startups', 'Anthropic', 'anthropic.com', 'inteligencia-artificial', array['ia', 'creditos', 'global', 'saas']::text[], 'Até US$ 100.000', 550000, 'De US$ 25 mil a US$ 100 mil+ em créditos de API do Claude, conforme o estágio da startup.', 'O programa de startups da Anthropic concede créditos para uso da API do Claude, permitindo que times early-stage construam produtos com modelos de ponta sem comprometer o caixa. O valor varia conforme o estágio da empresa e a relação com fundos parceiros, podendo ultrapassar US$ 100 mil para startups em rodadas mais avançadas.', array['Startup investida por um dos fundos de venture capital parceiros da Anthropic', 'Produto em desenvolvimento que utilize a API do Claude', 'Indicação feita diretamente pelo fundo parceiro']::text[], array['Verifique se o seu fundo investidor é parceiro do programa', 'Peça ao partner do fundo a indicação formal para a Anthropic', 'Crie uma conta na plataforma de API e aguarde a aplicação dos créditos']::text[], 'vc', 'https://www.anthropic.com/startups', true, false, true),
  ('google-cloud-para-startups', 'Google for Startups Cloud Program', 'Google Cloud', 'cloud.google.com', 'cloud', array['cloud', 'ia', 'creditos', 'global']::text[], 'Até US$ 350.000', 1900000, 'Até US$ 200 mil em créditos de infraestrutura (US$ 350 mil para startups de IA) ao longo de dois anos.', 'O programa de cloud do Google cobre custos de infraestrutura, banco de dados, Kubernetes e APIs de IA (incluindo Gemini e Vertex AI) por até dois anos. Startups de IA elegíveis acessam o teto ampliado do programa. Inclui suporte técnico, créditos de Workspace e acesso a especialistas.', array['Empresa fundada há menos de 5 anos (10 para startups de IA, conforme trilha)', 'Sem rodada Series A concluída no momento da inscrição (trilhas variam por estágio)', 'Não ter participado do programa anteriormente', 'Site institucional ativo e domínio próprio']::text[], array['Acesse a página do Google for Startups Cloud Program', 'Preencha o formulário com dados da empresa e do uso previsto de cloud', 'Vincule a conta de billing do Google Cloud para receber os créditos']::text[], 'condicoes', 'https://cloud.google.com/startup', true, false, true),
  ('aws-activate', 'AWS Activate', 'AWS', 'aws.amazon.com', 'cloud', array['cloud', 'ia', 'creditos', 'global']::text[], 'Até US$ 100.000', 550000, 'Até US$ 100 mil em créditos AWS para infraestrutura e IA via Bedrock — e até US$ 1 milhão para coortes selecionadas.', 'O AWS Activate é o maior programa de créditos de cloud do mundo. Startups bootstrapped começam com créditos menores na trilha aberta; empresas ligadas a aceleradoras e fundos parceiros acessam pacotes muito maiores, incluindo créditos para modelos de IA no Amazon Bedrock. Inclui suporte técnico, treinamentos e arquitetos de soluções.', array['Empresa com menos de 10 anos de fundação', 'Capital fechado (não listada em bolsa)', 'Não ter recebido créditos Activate anteriormente', 'Site e e-mail profissional da empresa']::text[], array['Crie uma conta AWS com o e-mail corporativo', 'Inscreva-se no AWS Activate (trilha Founders ou Portfolio)', 'Se estiver em aceleradora/fundo parceiro, informe o Org ID para o pacote ampliado']::text[], 'aberto', 'https://aws.amazon.com/activate', true, false, true),
  ('microsoft-for-startups', 'Microsoft for Startups', 'Microsoft', 'microsoft.com', 'cloud', array['cloud', 'ia', 'creditos', 'global', 'saas']::text[], 'Até US$ 150.000', 825000, 'Até US$ 150 mil em créditos Azure, além de GitHub Enterprise, Microsoft 365 e acesso a modelos OpenAI no Azure.', 'O Microsoft for Startups concede créditos Azure que escalam conforme o estágio da empresa, com acesso a modelos da OpenAI via Azure AI Foundry, GitHub Enterprise, Microsoft 365 e suporte técnico dedicado. É um dos pacotes mais completos para startups B2B e de IA.', array['Empresa com menos de 7 anos e receita anual abaixo de US$ 10 milhões', 'Desenvolvimento de produto próprio de software', 'Não ter participado do programa anteriormente', 'Site profissional ativo']::text[], array['Inscreva-se no portal do Microsoft for Startups', 'Descreva o produto e o estágio da empresa', 'Após aprovação, os créditos são liberados em níveis progressivos']::text[], 'condicoes', 'https://www.microsoft.com/startups', true, false, true),
  ('openai-para-startups', 'OpenAI para Startups', 'OpenAI', 'openai.com', 'inteligencia-artificial', array['ia', 'creditos', 'global']::text[], 'Até US$ 5.000', 27500, 'Créditos de API da OpenAI para startups early-stage, geralmente via fundos e aceleradoras parceiras.', 'A OpenAI distribui créditos de API por meio de parcerias com aceleradoras, fundos de VC e provedores de cloud. Os pacotes típicos ficam em torno de US$ 2.500 a US$ 5.000 e cobrem uso de GPT, embeddings, áudio e visão durante a fase de construção do produto.', array['Startup vinculada a aceleradora ou fundo parceiro da OpenAI', 'Conta de API ativa em nome da empresa']::text[], array['Confirme com sua aceleradora/fundo a disponibilidade do benefício', 'Solicite o código de resgate ao parceiro', 'Aplique o código na organização da API da OpenAI']::text[], 'vc', 'https://openai.com/form/startups', false, false, true),
  ('cloudflare-for-startups', 'Cloudflare for Startups', 'Cloudflare', 'cloudflare.com', 'creditos', array['cloud', 'creditos', 'global', 'gratuito']::text[], 'Até US$ 250.000', 1375000, 'Créditos escalonados de US$ 5 mil a US$ 250 mil conforme o estágio de funding, cobrindo CDN, Workers e R2.', 'O programa da Cloudflare cobre toda a plataforma — CDN, segurança, Workers (edge computing), R2 (storage sem taxa de egress) e Workers AI. Os créditos são escalonados por estágio, de bootstrapped a growth, e valem por um ano.', array['Startup construindo produto de software', 'Empresa com até 5 anos de fundação (regra geral)', 'Tier definido pelo estágio de captação']::text[], array['Inscreva-se no Cloudflare for Startups com a conta da empresa', 'Informe estágio de funding e investidores (se houver)', 'Créditos aplicados diretamente na conta após aprovação']::text[], 'aberto', 'https://www.cloudflare.com/forstartups/', false, false, true),
  ('zendesk-for-startups', 'Zendesk for Startups', 'Zendesk', 'zendesk.com', 'perks', array['saas', 'gratuito', 'global']::text[], 'Até US$ 80.000', 440000, 'Até 2 anos gratuitos na plataforma da Zendesk para até 50 agentes de suporte.', 'Startups aprovadas usam a plataforma de atendimento da Zendesk sem custo por até dois anos, com limite de 50 agentes — o suficiente para estruturar toda a operação de suporte sem mensalidade durante a fase de tração.', array['Empresa com menos de 10 anos', 'Rodada até Series B (sem Series C+)', 'Até 50 funcionários (ou 250 se indicada por parceiro)', 'Não ser cliente pago atual ou anterior da Zendesk']::text[], array['Inscreva-se no Zendesk for Startups', 'Comprove estágio e data de fundação', 'Ative o workspace gratuito após aprovação']::text[], 'condicoes', 'https://www.zendesk.com.br/campaign/startups/', false, false, true),
  ('mixpanel-startup-program', 'Mixpanel Startup Program', 'Mixpanel', 'mixpanel.com', 'perks', array['saas', 'gratuito', 'global']::text[], 'Até US$ 150.000', 825000, 'Um ano gratuito de Mixpanel com até 1 bilhão de eventos para analytics de produto.', 'O programa de startups da Mixpanel libera o plano completo de analytics de produto por um ano, com volume de até 1 bilhão de eventos — valor de mercado acima de US$ 150 mil. Ideal para times que querem instrumentar ativação, retenção e funis desde o início.', array['Empresa constituída há no máximo 5 anos', 'Captação total de até US$ 8 milhões', 'Não ser cliente pago atual da Mixpanel']::text[], array['Crie uma conta gratuita na Mixpanel', 'Inscreva-se no Startup Program com dados da empresa', 'Plano liberado automaticamente após validação']::text[], 'condicoes', 'https://mixpanel.com/startups', false, false, true),
  ('ibm-cloud-para-startups', 'IBM para Startups', 'IBM', 'ibm.com', 'cloud', array['cloud', 'ia', 'creditos', 'global']::text[], 'Até US$ 120.000', 660000, 'Até US$ 120 mil em créditos IBM Cloud para infraestrutura e IA (watsonx).', 'O programa da IBM concede créditos de cloud que podem ser usados em infraestrutura, Kubernetes, bancos de dados e na plataforma de IA watsonx. Bom encaixe para startups B2B que vendem para grandes empresas, pelo acesso ao ecossistema corporativo da IBM.', array['Empresa com menos de 5 anos', 'Receita anual abaixo de US$ 1 milhão', 'Não ser cliente atual da IBM Cloud', 'Produto minimamente viável (MVP) no ar']::text[], array['Inscreva-se no IBM para Startups', 'Apresente o MVP e o plano de uso de cloud', 'Créditos liberados em fases conforme o consumo']::text[], 'condicoes', 'https://www.ibm.com/startups', false, false, true),
  ('digitalocean-hatch', 'DigitalOcean Hatch', 'DigitalOcean', 'digitalocean.com', 'cloud', array['cloud', 'creditos', 'global']::text[], 'Até US$ 100.000', 550000, 'Créditos de infraestrutura na nuvem da DigitalOcean para startups ligadas a aceleradoras e fundos parceiros.', 'O Hatch é o programa de startups da DigitalOcean: créditos de infraestrutura (Droplets, Kubernetes, bancos gerenciados e GPUs) por 12 meses, com suporte prioritário. A porta de entrada é a rede de aceleradoras, incubadoras e fundos parceiros.', array['Empresa com menos de 5 anos', 'Participação em aceleradora, incubadora ou fundo aprovado', 'Não ter recebido créditos DigitalOcean antes', 'Site institucional ativo']::text[], array['Confirme se sua aceleradora/fundo é parceiro do Hatch', 'Inscreva-se com o código ou link do parceiro', 'Créditos aplicados na conta após aprovação']::text[], 'vc', 'https://www.digitalocean.com/hatch', false, false, true),
  ('datadog-for-startups', 'Datadog for Startups', 'Datadog', 'datadoghq.com', 'creditos', array['cloud', 'saas', 'creditos', 'global']::text[], 'Até US$ 100.000', 550000, 'Até US$ 100 mil em créditos para um ano de observabilidade com o Datadog Pro.', 'Startups early-stage ganham um ano de Datadog Pro — monitoramento de infraestrutura, APM, logs e dashboards — via parceiros do programa. O valor do pacote varia conforme o parceiro que faz a indicação.', array['Startup early-stage vinculada a parceiro do programa', 'Não ser cliente pago atual do Datadog']::text[], array['Verifique a lista de parceiros do Datadog for Startups', 'Solicite a indicação ao seu fundo ou aceleradora', 'Ative os créditos na criação da conta']::text[], 'condicoes', 'https://www.datadoghq.com/partner/datadog-for-startups/', false, false, true),
  ('notion-for-startups', 'Notion for Startups', 'Notion', 'notion.so', 'perks', array['saas', 'gratuito', 'global']::text[], 'Até US$ 12.000', 66000, '6 meses do plano Business com Notion AI incluído para organizar docs, wiki e projetos.', 'O Notion oferece seis meses gratuitos do plano Business (com IA ilimitada) para startups indicadas por parceiros — aceleradoras, fundos e comunidades. É o suficiente para estruturar wiki, CRM leve e gestão de projetos sem custo no primeiro ano.', array['Startup com até 50 funcionários', 'Indicação por parceiro do programa (fundo, aceleradora ou comunidade)', 'Workspace novo ou em plano gratuito']::text[], array['Obtenha o link/código com o parceiro', 'Inscreva-se na página do Notion for Startups', 'Benefício aplicado ao workspace após validação']::text[], 'aberto', 'https://www.notion.com/startups', false, false, true),
  ('github-for-startups', 'GitHub for Startups', 'GitHub', 'github.com', 'perks', array['saas', 'gratuito', 'global']::text[], '20 assentos Enterprise', 120000, 'GitHub Enterprise gratuito no primeiro ano (até 20 assentos) e 50% no segundo, para startups de fundos parceiros.', 'O GitHub for Startups dá acesso ao plano Enterprise — incluindo recursos avançados de segurança e o Copilot em planos elegíveis — sem custo no primeiro ano e com desconto no segundo. A inscrição passa pelos fundos e aceleradoras parceiros.', array['Startup até Series A', 'Vinculada a fundo ou aceleradora parceira', 'Nova no GitHub Enterprise']::text[], array['Confirme a parceria com seu investidor', 'Inscreva-se na página do GitHub for Startups', 'Upgrade aplicado à organização após aprovação']::text[], 'vc', 'https://github.com/enterprise/startups', false, false, true),
  ('nvidia-inception', 'NVIDIA Inception', 'NVIDIA', 'nvidia.com', 'programas', array['ia', 'global', 'gratuito']::text[], 'Benefícios variados', 200000, 'Programa gratuito para startups de IA: descontos em GPUs, créditos de cloud parceiros e acesso técnico à NVIDIA.', 'O Inception é o programa global da NVIDIA para startups de IA e computação acelerada. Sem custo e sem equity, dá acesso a descontos em hardware, créditos em clouds parceiras, treinamentos do Deep Learning Institute e visibilidade junto a fundos do ecossistema.', array['Startup de IA, ML ou computação acelerada', 'Empresa constituída com site ativo', 'Sem limite rígido de estágio — early stage é bem-vindo']::text[], array['Inscreva-se no portal do NVIDIA Inception', 'Descreva o produto e o uso de GPU/IA', 'Acesso liberado ao hub de benefícios após aprovação']::text[], 'aberto', 'https://www.nvidia.com/en-us/startups/', false, false, true),
  ('stripe-atlas', 'Stripe Atlas', 'Stripe', 'stripe.com', 'perks', array['fintech', 'saas', 'global']::text[], 'US$ 500 + perks', 100000, 'Incorporação de empresa nos EUA (Delaware C-Corp) em poucos dias, com créditos e benefícios de dezenas de parceiros.', 'O Stripe Atlas resolve a constituição de uma C-Corp em Delaware — passo comum para startups brasileiras que captam com fundos internacionais. Inclui emissão de equity para fundadores, EIN, conta bancária via parceiros e um pacote de créditos e descontos em ferramentas.', array['Fundadores de qualquer país (incluindo Brasil)', 'Pagamento da taxa única do serviço']::text[], array['Crie a conta no Stripe Atlas e preencha os dados da empresa', 'Assine os documentos eletronicamente', 'Receba EIN, documentos e acesso aos perks']::text[], 'aberto', 'https://stripe.com/atlas', false, false, true),
  ('y-combinator', 'Y Combinator', 'Y Combinator', 'ycombinator.com', 'aceleradoras', array['aceleradoras', 'global']::text[], 'US$ 500.000', 2750000, 'A aceleradora mais conhecida do mundo: US$ 500 mil em investimento padrão e acesso à maior rede de founders.', 'O YC investe US$ 500 mil em cada startup aceita (deal padrão: US$ 125 mil por 7% + US$ 375 mil em SAFE uncapped MFN). Além do capital, o programa de 3 meses dá acesso a parceiros, Demo Day e a um pacote enorme de créditos de cloud e ferramentas. Startups brasileiras são aceitas regularmente.', array['Aplicação aberta a fundadores de qualquer país', 'Ideia ou produto em qualquer estágio inicial', 'Disponibilidade para o batch (presencial em São Francisco)']::text[], array['Preencha a aplicação online dentro do prazo do batch', 'Se selecionado, participe da entrevista (remota)', 'Aceite o investimento e participe do programa']::text[], 'condicoes', 'https://www.ycombinator.com/apply', false, false, true),
  ('fapesp-pipe', 'FAPESP PIPE — Pesquisa Inovativa em Pequenas Empresas', 'FAPESP', 'fapesp.br', 'editais', array['editais', 'brasil', 'gratuito']::text[], 'Até R$ 2 milhões', 2000000, 'Fomento não reembolsável para P&D em pequenas empresas paulistas — até R$ 2 milhões somando as fases do programa.', 'O PIPE financia pesquisa e desenvolvimento de inovação em empresas com até 250 funcionários sediadas no Estado de São Paulo. O recurso é não reembolsável (não vira dívida nem equity): a Fase 1 valida a viabilidade técnica e a Fase 2 desenvolve a tecnologia, com bolsas e custeio do projeto.', array['Empresa sediada no Estado de São Paulo', 'Até 250 funcionários', 'Projeto de pesquisa com desafio tecnológico real', 'Pesquisador responsável vinculado à empresa']::text[], array['Leia o edital vigente no site da FAPESP', 'Monte o projeto de pesquisa no formato exigido (SAGe)', 'Submeta e acompanhe a avaliação por assessores científicos']::text[], 'condicoes', 'https://fapesp.br/pipe', true, false, true),
  ('finep-startup', 'Finep Startup', 'Finep', 'finep.gov.br', 'editais', array['editais', 'brasil']::text[], 'Até R$ 1 milhão', 1000000, 'Investimento direto da Finep em startups inovadoras via contrato de opção de compra de participação.', 'O Finep Startup aporta recursos públicos em startups de base tecnológica por meio de instrumento conversível, sem tomada imediata de participação. O foco é acelerar empresas com produto inovador e potencial de escala, em chamadas públicas periódicas por setor.', array['Empresa brasileira de base tecnológica', 'Receita e tempo de fundação dentro dos limites da chamada vigente', 'Produto inovador validado ou em validação']::text[], array['Acompanhe as chamadas públicas no site da Finep', 'Submeta o plano de negócios e os documentos da empresa', 'Participe das bancas de avaliação e diligência']::text[], 'condicoes', 'https://www.finep.gov.br/apoio-e-financiamento-externa/programas-e-linhas/finep-startup', true, false, true),
  ('bndes-garagem', 'BNDES Garagem', 'BNDES', 'bndes.gov.br', 'programas', array['brasil', 'aceleradoras', 'gratuito']::text[], 'Aceleração gratuita', 150000, 'Programa de aceleração do BNDES para startups de impacto, com mentorias, conexões e apoio ao desenvolvimento de negócios — sem equity.', 'O BNDES Garagem acelera startups brasileiras em ciclos temáticos (govtech, impacto socioambiental, economia verde, entre outros), oferecendo trilha de capacitação, mentorias com especialistas e conexão com grandes empresas e órgãos públicos — sem cobrar participação societária.', array['Startup brasileira com CNPJ ativo', 'Aderência ao tema do ciclo vigente', 'Produto em validação ou tração']::text[], array['Acompanhe a abertura dos ciclos no site do BNDES Garagem', 'Inscreva-se no edital com pitch e dados da empresa', 'Participe das etapas de seleção e do programa']::text[], 'aberto', 'https://www.bndesgaragem.com.br', false, false, true),
  ('sebrae-para-startups', 'Sebrae para Startups (Capital Empreendedor e Inovativa)', 'Sebrae', 'sebrae.com.br', 'programas', array['brasil', 'gratuito', 'editais']::text[], 'Capacitação + conexões', 50000, 'Programas gratuitos do Sebrae que preparam startups para captação e conectam fundadores a investidores em todo o Brasil.', 'O Sebrae mantém trilhas nacionais para startups: o Capital Empreendedor prepara a empresa para captar investimento e a conecta a fundos e investidores-anjo; o InovAtiva (em parceria com o MDIC) é o maior programa gratuito de aceleração da América Latina, com mentorias e demoday nacional.', array['Startup brasileira com CNPJ', 'Qualquer estágio — ideação a tração, conforme a trilha', 'Inscrição nos ciclos abertos']::text[], array['Inscreva-se no ciclo aberto do programa escolhido', 'Complete a trilha de capacitação online', 'Participe das bancas e rodadas de conexão com investidores']::text[], 'aberto', 'https://sebrae.com.br/sites/PortalSebrae/inovacao', false, false, true),
  ('inovativa-brasil', 'InovAtiva Brasil', 'InovAtiva', 'inovativa.online', 'aceleradoras', array['brasil', 'aceleradoras', 'gratuito']::text[], 'Aceleração gratuita', 80000, 'O maior programa gratuito de aceleração da América Latina — mentoria, capacitação e demoday, sem equity.', 'Mantido pelo MDIC e Sebrae, o InovAtiva já acelerou milhares de startups brasileiras. O programa é 100% gratuito e não pede participação societária: inclui mentorias individuais com executivos, trilha de conteúdo e apresentação para investidores e corporates no demoday nacional.', array['Startup brasileira de base tecnológica', 'Produto lançado ou MVP em validação', 'Inscrição dentro do ciclo semestral']::text[], array['Inscreva-se gratuitamente no ciclo vigente', 'Passe pela seleção de pitch e formulário', 'Conclua a jornada de aceleração e o demoday']::text[], 'aberto', 'https://www.inovativa.online', false, false, true),
  ('cubo-itau', 'Cubo Itaú', 'Cubo', 'cubo.network', 'programas', array['brasil', 'saas', 'fintech']::text[], 'Hub + conexões', 100000, 'Um dos maiores hubs de inovação da América Latina: residência em São Paulo, conexão com corporates e comunidade de startups.', 'O Cubo, mantido pelo Itaú e parceiros, seleciona startups com tração para integrar sua comunidade — com espaço físico na Vila Olímpia, agenda de negócios com grandes empresas patrocinadoras e acesso a um ecossistema denso de founders, fundos e clientes corporativos.', array['Startup com produto no mercado e receita recorrente', 'Aderência aos verticais do hub (fintech, saúde, varejo, agro etc.)', 'Processo seletivo contínuo']::text[], array['Inscreva-se no site do Cubo', 'Participe da avaliação de tração e fit', 'Assine o plano de residência (físico ou digital)']::text[], 'condicoes', 'https://cubo.network', false, false, true),
  ('google-for-startups-brasil', 'Google for Startups Brasil', 'Google for Startups', 'startup.google.com', 'programas', array['brasil', 'ia', 'gratuito', 'aceleradoras']::text[], 'Aceleração + créditos', 1900000, 'Programas de aceleração do Google no Brasil (incluindo trilhas de IA), sem equity, com mentoria e créditos de cloud.', 'O Google for Startups mantém no Brasil programas de aceleração sem participação societária — incluindo edições dedicadas a IA e a fundadores negros (Black Founders Fund, com aporte não diluitivo). Participantes recebem mentoria de times do Google, créditos de Google Cloud e acesso à rede global.', array['Startup brasileira com produto lançado', 'Aderência ao foco do ciclo (IA, impacto, etc.)', 'Time dedicado em tempo integral']::text[], array['Acompanhe a abertura das turmas no site do Google for Startups', 'Envie a aplicação com métricas e pitch', 'Participe das entrevistas de seleção']::text[], 'condicoes', 'https://startup.google.com/intl/pt_br/', true, false, true),
  ('ace-startups', 'ACE Cortex / ACE Startups', 'ACE', 'ace.vc', 'aceleradoras', array['brasil', 'aceleradoras']::text[], 'Investimento + aceleração', 500000, 'Uma das aceleradoras pioneiras do Brasil: investimento pré-seed, metodologia própria e rede de mentores.', 'A ACE acelera e investe em startups brasileiras early-stage há mais de uma década, com cheques pré-seed, metodologia estruturada de tração e acesso a uma rede ampla de mentores, fundos e corporates para rodadas seguintes.', array['Startup brasileira early-stage (pré-seed/seed)', 'Time fundador dedicado', 'Produto em validação com sinais de tração']::text[], array['Inscreva-se no funil contínuo da ACE', 'Participe das etapas de avaliação e entrevistas', 'Negocie termos de investimento e aceleração']::text[], 'condicoes', 'https://ace.vc', false, false, true),
  ('bndes-credito-inovacao', 'BNDES Crédito Inovação', 'BNDES', 'bndes.gov.br', 'editais', array['brasil', 'editais']::text[], 'Financiamento subsidiado', 3000000, 'Linhas de financiamento do BNDES com juros reduzidos para projetos de inovação e transformação digital.', 'O BNDES opera linhas de crédito dedicadas a inovação — com taxas menores que o mercado e prazos longos — para empresas que investem em P&D, desenvolvimento de produtos e transformação digital. Para startups com receita, é alternativa de capital não dilutivo.', array['Empresa brasileira com faturamento e capacidade de crédito', 'Projeto de inovação estruturado', 'Análise de crédito via BNDES ou agente financeiro']::text[], array['Estruture o projeto de inovação com orçamento e cronograma', 'Submeta via Canal MPME ou diretamente ao BNDES', 'Passe pela análise de crédito e contrate a operação']::text[], 'condicoes', 'https://www.bndes.gov.br/wps/portal/site/home/financiamento/produto/bndes-credito-inovacao', false, false, true),
  ('cnpq-rhae', 'CNPq — Bolsas e Fomento (RHAE)', 'CNPq', 'cnpq.br', 'editais', array['brasil', 'editais', 'gratuito']::text[], 'Bolsas de pesquisa', 300000, 'Bolsas do CNPq para inserir mestres e doutores em projetos de P&D dentro de empresas privadas.', 'O programa RHAE do CNPq paga bolsas para pesquisadores (mestres e doutores) trabalharem em projetos de inovação dentro de micro, pequenas e médias empresas — reduzindo o custo de montar um time técnico de P&D na startup.', array['Micro, pequena ou média empresa brasileira', 'Projeto de P&D com pesquisador qualificado', 'Submissão dentro do edital vigente']::text[], array['Acompanhe os editais RHAE no site do CNPq', 'Cadastre o projeto na Plataforma Carlos Chagas', 'Indique os bolsistas após aprovação']::text[], 'condicoes', 'https://www.gov.br/cnpq/pt-br', false, false, true),
  ('darwin-startups', 'Darwin Startups', 'Darwin', 'darwinstartups.com', 'aceleradoras', array['brasil', 'aceleradoras', 'fintech']::text[], 'Investimento pré-seed', 300000, 'Aceleradora catarinense com investimento pré-seed e foco em startups B2B e fintechs.', 'A Darwin investe cheques pré-seed em startups brasileiras e roda programas intensivos de aceleração com foco em tração comercial B2B, conectando fundadores a fundos e clientes corporativos do Sul do país e além.', array['Startup brasileira early-stage', 'Modelo B2B ou fintech (preferencial)', 'Disponibilidade para o programa intensivo']::text[], array['Inscreva-se no batch aberto', 'Participe das entrevistas e análise', 'Feche o investimento e inicie a aceleração']::text[], 'condicoes', 'https://darwinstartups.com', false, false, true),
  ('vercel-for-startups', 'Vercel for Startups', 'Vercel', 'vercel.com', 'creditos', array['cloud', 'saas', 'creditos', 'global']::text[], 'Créditos de plataforma', 60000, 'Créditos na plataforma da Vercel para hospedar aplicações Next.js com escala global.', 'Startups ligadas a aceleradoras e fundos parceiros recebem créditos na Vercel para deploy de aplicações front-end e full-stack — incluindo recursos de IA (AI SDK) e infraestrutura serverless, sem custo durante a fase inicial.', array['Startup early-stage vinculada a parceiro', 'Projeto hospedado (ou a hospedar) na Vercel']::text[], array['Solicite o benefício via parceiro ou formulário da Vercel', 'Vincule o time da empresa na plataforma', 'Créditos aplicados na fatura mensal']::text[], 'condicoes', 'https://vercel.com/startups', false, false, true),
  ('supabase-para-startups', 'Supabase Launch Week Credits', 'Supabase', 'supabase.com', 'creditos', array['cloud', 'saas', 'creditos', 'global', 'gratuito']::text[], 'Créditos de plataforma', 30000, 'Créditos do Supabase para startups de aceleradoras parceiras (YC, entre outras) usarem Postgres, Auth e Storage gerenciados.', 'O Supabase distribui créditos por meio de parcerias com aceleradoras e programas de startups, cobrindo banco PostgreSQL gerenciado, autenticação, storage e edge functions — uma alternativa open source ao Firebase para o backend da startup.', array['Startup em aceleradora parceira ou programa de deals', 'Organização nova ou em plano gratuito']::text[], array['Resgate o código pelo portal de perks da sua aceleradora', 'Aplique o código na organização do Supabase', 'Faça o upgrade do projeto para o plano Pro']::text[], 'vc', 'https://supabase.com', false, false, true)
on conflict (slug) do nothing;

insert into public.blog_posts
  (slug, title, excerpt, content, cover_image, author, reading_min, published) values
  ('como-conseguir-creditos-aws-startup-brasileira', 'Como conseguir créditos AWS para sua startup brasileira (guia 2026)', 'O AWS Activate pode cobrir sua infraestrutura por 1 a 2 anos. Veja o passo a passo real para startups brasileiras, com e sem aceleradora.', 'O AWS Activate é o caminho mais comum para uma startup brasileira zerar a conta de cloud nos primeiros anos. Mas o valor que você recebe depende muito de **como** você entra no programa.

## As duas portas de entrada

**1. Trilha Founders (sem indicação).** Aberta a qualquer startup com CNPJ ou C-Corp, site profissional e e-mail corporativo. Os créditos iniciais são menores, mas o processo é simples e a aprovação costuma sair em poucos dias.

**2. Trilha Portfolio (com indicação).** Se a sua startup participa de uma aceleradora, incubadora ou tem investimento de um fundo parceiro da AWS, você recebe um **Org ID** do parceiro e acessa pacotes muito maiores — que podem chegar a US$ 100 mil, e a até US$ 1 milhão em coortes selecionadas de IA.

## Checklist antes de aplicar

- Site no ar com domínio próprio (nada de página no Notion)
- E-mail corporativo no mesmo domínio
- Conta AWS criada em nome da empresa, não do fundador
- Empresa com menos de 10 anos e capital fechado
- Nunca ter recebido créditos Activate antes

## Dicas que aumentam a aprovação

1. Descreva o produto de forma específica: o que ele faz, para quem, e como usa a AWS.
2. Se estiver em programa como InovAtiva, Cubo ou ACE, **pergunte pelo Org ID** — muitos founders deixam dinheiro na mesa por não saber que o parceiro é credenciado.
3. Use os créditos com calma: eles têm validade (normalmente 1 a 2 anos). Arquitete para não criar custos que você não conseguirá pagar quando os créditos acabarem.

## E depois que os créditos acabam?

Negocie. A AWS tem times de startups no Brasil e oferece *private pricing* e descontos por compromisso de uso (Savings Plans). Startups que mostram crescimento conseguem condições bem melhores do que o preço de tabela.

> Regra de ouro: trate crédito de cloud como extensão de runway, não como desculpa para desperdiçar infraestrutura.', null, 'Equipe Crédito para Startups', 7, true),
  ('como-conseguir-creditos-openai-anthropic', 'Como conseguir créditos de IA: OpenAI, Anthropic e Google em 2026', 'APIs de IA são o novo custo de cloud. Veja como startups brasileiras conseguem créditos da OpenAI, Anthropic e Google para construir produtos de IA.', 'Se a sua startup constrói produto com LLMs, a conta de API pode crescer mais rápido que a de infraestrutura. A boa notícia: os três grandes laboratórios têm programas de créditos — cada um com uma porta de entrada diferente.

## OpenAI

A OpenAI distribui créditos principalmente **via parceiros**: aceleradoras, fundos e provedores de cloud. Os pacotes típicos ficam entre US$ 2.500 e US$ 5.000. Se você está em uma aceleradora, verifique o portal de perks antes de pagar a primeira fatura.

## Anthropic (Claude)

O programa da Anthropic é mais generoso — de US$ 25 mil a mais de US$ 100 mil em créditos de API — mas a entrada padrão é por **indicação de fundos parceiros**. Se sua startup é investida, peça ao partner do fundo para verificar a parceria. O Claude também entra no pacote de créditos da AWS (via Bedrock) e do Google Cloud (via Vertex AI), o que é um atalho útil.

## Google (Gemini / Vertex AI)

O caminho aqui é o **Google for Startups Cloud Program**: os créditos de cloud valem para as APIs de IA, e startups de IA acessam o teto ampliado do programa (até US$ 350 mil em dois anos). Para quem roda tudo no GCP, é o pacote mais completo.

## Estratégia: empilhe créditos sem violar regras

- Os programas de cloud (AWS, GCP, Azure) **podem coexistir** — nada impede ter créditos nos três.
- Créditos de modelo via cloud (Bedrock, Vertex) contam como crédito de cloud, então você pode usá-los **além** dos créditos diretos do laboratório.
- Leia os termos: alguns programas vetam participação anterior ou exigem exclusividade temporária de workload.

## Ordem sugerida para uma startup de IA no Brasil

1. AWS Activate ou Google Cloud (infra + modelos via Bedrock/Vertex)
2. Programa direto do laboratório que você mais usa (OpenAI ou Anthropic)
3. NVIDIA Inception para descontos de GPU e créditos extras de parceiros', null, 'Equipe Crédito para Startups', 8, true),
  ('melhores-programas-para-startups-brasileiras', 'Os melhores programas para startups brasileiras em 2026', 'Do Sebrae à FAPESP, do Cubo ao Google for Startups: um mapa do fomento e da aceleração disponíveis para quem empreende no Brasil.', 'O ecossistema brasileiro tem uma vantagem pouco explorada: uma camada inteira de fomento público e programas gratuitos que não existe em muitos países. Este é o mapa.

## Fomento público (dinheiro não dilutivo)

**FAPESP PIPE** — para empresas paulistas com projeto de P&D. Recursos não reembolsáveis que podem passar de R$ 2 milhões somando as fases. É o programa mais robusto de pesquisa aplicada em empresa do país.

**Finep Startup** — aporte público via instrumento conversível para startups de base tecnológica, em chamadas periódicas.

**BNDES** — linhas de crédito para inovação com juros subsidiados, além do BNDES Garagem (aceleração gratuita, sem equity).

**CNPq RHAE** — bolsas para colocar mestres e doutores dentro do time de P&D da sua empresa.

## Aceleração gratuita

**InovAtiva Brasil** — o maior programa gratuito de aceleração da América Latina (MDIC + Sebrae). Mentoria, trilha de conteúdo e demoday nacional, sem equity.

**Sebrae Capital Empreendedor** — prepara a startup para captação e conecta com investidores.

**Google for Startups Brasil** — turmas de aceleração sem equity, incluindo trilhas de IA e o Black Founders Fund (aporte não dilutivo).

## Hubs e comunidades

**Cubo Itaú** — residência e agenda de negócios com corporates em São Paulo. **ACE** e **Darwin** — aceleradoras com investimento pré-seed.

## Como combinar tudo

1. Comece pelo gratuito: InovAtiva ou Sebrae para estruturar pitch e métricas.
2. Se há P&D de verdade, rode FAPESP/Finep em paralelo — o ciclo é longo, então quanto antes, melhor.
3. Créditos de cloud e IA (AWS, Google, Microsoft) entram em qualquer estágio e liberam caixa imediato.
4. Hub ou aceleradora com equity só quando o valor da rede superar o custo da diluição.', null, 'Equipe Crédito para Startups', 9, true),
  ('como-reduzir-custos-de-infraestrutura-startup', 'Como reduzir custos de infraestrutura na sua startup (sem reescrever tudo)', 'Créditos, arquitetura enxuta e negociação: um plano prático para cortar a conta de cloud em até 80% nos primeiros anos.', 'Infraestrutura é o segundo maior custo de muitas startups de software — e o mais fácil de atacar. O plano abaixo segue a ordem de esforço: do que dá resultado hoje ao que exige mudança de arquitetura.

## 1. Créditos primeiro (resultado imediato)

Antes de otimizar qualquer coisa, garanta que você não está pagando o que poderia ser grátis:

- **AWS Activate, Google Cloud ou Microsoft for Startups** — escolha a nuvem principal e aplique.
- **Cloudflare for Startups** — CDN, segurança e R2 (storage sem taxa de saída de dados).
- **Datadog / Mixpanel / Zendesk** — observabilidade, analytics e suporte com 1 a 2 anos gratuitos.

Uma startup early-stage bem organizada opera 12 a 24 meses com custo de infraestrutura próximo de zero só com esses programas.

## 2. Higiene básica (primeira semana)

- Desligue ambientes de staging fora do horário comercial.
- Apague recursos órfãos: volumes, IPs elásticos e snapshots esquecidos.
- Configure alertas de billing com teto por serviço.
- Revise instâncias superdimensionadas — o padrão é começar grande "por garantia".

## 3. Arquitetura enxuta (primeiro trimestre)

- Prefira serviços gerenciados com plano gratuito generoso (Postgres gerenciado, filas, storage de objetos).
- Egress é o imposto invisível da cloud: mantenha dados e computação na mesma região e use CDN para estáticos.
- Serverless para cargas irregulares; instâncias reservadas para cargas constantes.

## 4. Negocie (quando os créditos acabarem)

Com 12+ meses de histórico de consumo, fale com o time de startups do seu provedor. Savings Plans, descontos por compromisso e *private pricing* são padrão para quem pergunta — e invisíveis para quem não pergunta.

> Meta realista: conta de infraestrutura abaixo de 5% da receita até a Série A.', null, 'Equipe Crédito para Startups', 7, true)
on conflict (slug) do nothing;
